/********************************************************************
 * Version        Date          Name            Description
 * ==================================================================
 * V1.0         13-01-2022      Rakesh          Add Method implementation
 * 
**********************************************************************/

public with sharing class Calculator {
    public Calculator() {

    }    
    public integer add(integer a, integer b) {
        return a+b; 
    }
    
}